default_language_version:
  python: python3.14
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
        exclude: ^\.gitlab-ci\.yml$
    -   id: debug-statements
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
    -   id: autoflake
-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]

-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    -   id: black
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update

-   repo: local
    hooks:
    -   id: ty
        name: ty
        entry: ty
        args: ["check", "--python", ".venv", "src/"]
        language: python
        language_version: python3.14
        additional_dependencies: ["ty"]
        pass_filenames: false
        require_serial: true
        verbose: true
